version: '3'

services:
  web:
    build:
      context: ./.docker/nginx
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
    env_file:
      - ./.docker/.env.nginx.local

  php:
    build:
      context: ./.docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - .:/var/www/html
